package uk.co.ii.financialtoolsservice.financeApp.service;


import uk.co.ii.financialtoolsservice.financeApp.dto.Greeting;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

@Component
public class GreetingHandler {

    public Mono<ServerResponse> sayHello(ServerRequest request){

        return ServerResponse.ok().contentType(MediaType.APPLICATION_JSON)
                .body(BodyInserters.fromValue(Greeting
                        .builder()
                        .message(" Hello Reactive Response From Service layer")
                        .build()),Greeting.class );

    }

    /**
     * It could return many other things,
     *  including a stream of items from a database, a stream of items that were generated by calculations, and so on.
     *  Note the reactive code: a Mono object that holds a ServerResponse body.
     */
}
